doc-warnings: no
test-warnings: no
strictness: veryhigh
max-line-length: 120
autodetect: yes
requirements:
  - requirements.txt
ignore-paths:
  - docs
mccabe:
  run: false
pep8:
  disable:
    - C0103
pylint:
  disable:
    - R0903
    - C0103
    - R0913
    - R0904
    - W0142
    - R0902
    - R0912
    - R0913
    - R0914
    - R0915
