language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install tox-travis
# command to run tests
script: tox
# run in a docker container
sudo: false
notifications:
  email: false
deploy:
  provider: pypi
  user: bkabrda
  on:
    tags: true
  password:
    secure: Q4pXe0ARf2Mj7ZEqEICpzW6SBB554PxVPKErJkUcaD4V3zO3e/Ckbrk0aHeCMCPZlD5i/tfBXRMsMJhcvQht+jXTwUo5VD55WvkKBmpvQbJBsvmrIvrX+3C8SxVYXyLiSklQxCdGMCE/EN9dmQVI2574BQsXR43uVhwOzuL2V3k=
